apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lhim6x0xa-python
  janus-idp.io/tekton: lhim6x0xa-python
  backstage.io/kubernetes-id: lhim6x0xa-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lhim6x0xa-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
