apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lhim6x0xa-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lhim6x0xa-python 
  name: lhim6x0xa-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lhim6x0xa-python 
